name: "auto-release"

on:
  push:
    branches:
      - "master"

jobs:
  pre-release:
    name: "Auto Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@master
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel
      - name: Build
        run: |
          python setup.py sdist bdist_wheel
          pip install dist/*.whl
          export PACKAGE_VERSION=$(python -c "import log21; print(log21.__version__)")
          echo "PACKAGE_VERSION=$PACKAGE_VERSION"
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ env.PACKAGE_VERSION }}"
          title: "Auto Build"
          files: |
            dist/*
