name: "auto-release"

on:
  push:
    branches:
      - "master"

jobs:
  pre-release:
    name: "Auto Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@master
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build setuptools wheel

      - name: Build
        run: |
          python -m build
          pip install dist/*.whl
          echo "PACKAGE_VERSION=$(python -c 'import log21; print(log21.__version__)')" >> $GITHUB_ENV

      - name: check-version
        uses: actions-ecosystem/action-regex-match@v2
        id: check-version
        with:
          text: ${{ env.PACKAGE_VERSION }}
          regex: '\d+\.\d+\.\d+a\d+'

      - uses: "marvinpinto/action-automatic-releases@latest"
        if: ${{ steps.check-version.outputs.match == '' }}  # If didn't match
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ env.PACKAGE_VERSION }}"
          title: "Auto Build"
          files: |
            dist/*
